variables:
  DOCKER_TLS_CERTDIR: "/certs"
  CRYTON_APP_DIRECTORY: "$CI_PROJECT_DIR/cryton/"
  UV_CACHE_DIR: "$CI_PROJECT_DIR/.uv-cache"
  UV_LINK_MODE: copy
  UV_PYTHON_CACHE_DIR: "$UV_CACHE_DIR/python"
  UV_PYTHON_INSTALL_DIR: "$CI_PROJECT_DIR/.uv-python"
  CACHE_UV_CACHE_POLICY: pull

default:
  image: ghcr.io/astral-sh/uv:0.12.5-debian
  interruptible: true
  artifacts:
    expire_in: 30 days
  cache:
    - key:
        files:
          - uv.lock
        prefix: uv
      paths:
        - .uv-cache/
      policy: $CACHE_UV_CACHE_POLICY
    - key:
        files:
          - .python-versions
        prefix: python
      paths:
        - .uv-python/
      policy: $CACHE_UV_CACHE_POLICY

stages:
  - setup
  - test
  - publish
  - build
  - deploy

uv_install:
  stage: setup
  variables:
    CACHE_UV_CACHE_POLICY: pull-push
  script:
    - uv python install --upgrade
    - uv sync --frozen --all-groups --all-extras
    - uv cache prune --ci

.documentation:
  rules:
    - changes:
        - mkdocs.yml
        - docs/**/*
        - .gitlab-ci.yml
    - when: never

# tests
.tests:
  stage: test
  coverage: '/TOTAL.*\s+(\d+%)$/'
  rules:
    - changes:
        - src/**/*
        - tests/**/*
        - .coveragerc-*
        - settings*
        - .gitlab-ci.yml
        - uv.lock
        - pyproject.toml
        - tox.ini
    - when: never

unit_tests:
  extends: .tests
  script:
    - uv run tox run-parallel -- tests/unit/ --cov=cryton --cov-config=.coveragerc-unit
    - cat coverage.readable

integration_tests:
  extends: .tests
  script:
    - uv run tox run-parallel -- tests/integration/ --cov=cryton --cov-config=.coveragerc-integration
    - cat coverage.readable

format:
  stage: test
  rules:
    - changes:
        - src/**/*
        - tests/**/*
        - .gitlab-ci.yml
        - uv.lock
        - pyproject.toml
    - when: never
  before_script:
    - uv sync --locked --all-extras --group dev
  script:
    - uv run ruff format --check --diff src tests

build_documentation:
  extends: .documentation
  stage: test
  before_script:
    - uv sync --locked --group docs
  script:
    - uv run mkdocs build

# publish
.publish:
  stage: publish
  rules:
    - if: $CI_COMMIT_TAG =~ /^[0-9]+\.[0-9]+\.([0-9]|[0-z])+$/ && $CI_COMMIT_REF_PROTECTED == "true"

.build_docker_image:
  extends: .publish
  cache: []
  image:
    name: gcr.io/kaniko-project/executor:debug
    entrypoint: [ "" ]
  variables:
    BUILD_TARGET: "production"
    IMAGE_NAME_POSTFIX: ""
    DOCKERFILE: "Dockerfile"
  before_script:
    # Set variables
    - export IMAGE_TAG_CURRENT=$CI_COMMIT_TAG
    - export IMAGE_TAG_MINOR=${IMAGE_TAG_CURRENT%.*}
    - export IMAGE_TAG_MAJOR=${IMAGE_TAG_MINOR%.*}
    - export IMAGE_DESTINATION=$CI_REGISTRY_IMAGE/$IMAGE_NAME_POSTFIX
    # Check variables
    - echo "IMAGE_DESTINATION $IMAGE_DESTINATION"
    - echo "BUILD_TARGET $BUILD_TARGET"
    - echo "IMAGE_TAG_CURRENT $IMAGE_TAG_CURRENT"
    - echo "IMAGE_TAG_MINOR $IMAGE_TAG_MINOR"
    - echo "IMAGE_TAG_MAJOR $IMAGE_TAG_MAJOR"
  script:
    - echo "{\"auths\":{\"${CI_REGISTRY}\":{\"username\":\"${CI_REGISTRY_USER}\",\"password\":\"${CI_REGISTRY_PASSWORD}\"}}}" > /kaniko/.docker/config.json
    - /kaniko/executor
      --context $CI_PROJECT_DIR
      --dockerfile $DOCKERFILE
      --target $BUILD_TARGET
      --skip-unused-stages
      --destination $IMAGE_DESTINATION:$IMAGE_TAG_CURRENT
      --destination $IMAGE_DESTINATION:$IMAGE_TAG_MINOR
      --destination $IMAGE_DESTINATION:$IMAGE_TAG_MAJOR
      --destination $IMAGE_DESTINATION:latest
      --label version="$IMAGE_TAG_CURRENT"
      --label commit="$CI_COMMIT_SHA"

upload_package_to_pypi:
  extends: .publish
  script:
    - uv build
    - uv publish --token "$PYPI_TOKEN"

build_docker_image_hive:
  extends: .build_docker_image
  variables:
    IMAGE_NAME_POSTFIX: "hive"
    DOCKERFILE: "Dockerfile-hive"

build_docker_image_api_proxy:
  extends: .build_docker_image
  variables:
    IMAGE_NAME_POSTFIX: "api-proxy"
    DOCKERFILE: "Dockerfile-api-proxy"

build_docker_image_cli:
  extends: .build_docker_image
  variables:
    IMAGE_NAME_POSTFIX: "cli"
    DOCKERFILE: "Dockerfile-cli"

build_docker_image_worker:
  extends: .build_docker_image
  variables:
    IMAGE_NAME_POSTFIX: "worker"
    DOCKERFILE: "Dockerfile-worker"

# Build and deploy pages
pages:
  extends: .documentation
  stage: build
  variables:
    HTTPS_REMOTE: https://${BOT_SHAKESPEARE_NAME}:${BOT_SHAKESPEARE_TOKEN}@${CI_SERVER_HOST}/${CI_PROJECT_PATH}.git
    PAGES_BRANCH: "pages"
  before_script:
    - git config user.name $BOT_SHAKESPEARE_NAME
    - git config user.email $BOT_SHAKESPEARE_NAME@asd.asd
    - git remote remove origin
    - git remote add origin $HTTPS_REMOTE
    - git branch -D $PAGES_BRANCH || echo "Branch not present."
    - git fetch --depth=1 origin $PAGES_BRANCH || echo "Branch doesn't exist yet."
    - uv sync --locked --group docs
  rules:
    - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH && $CI_COMMIT_REF_PROTECTED == "true"
    - if: $CI_COMMIT_TAG =~ /^[0-9]+\.[0-9]+|x\.([0-9]|[0-z])+$/ && $CI_COMMIT_REF_PROTECTED == "true"
  script:
    - |
      if [[ "$CI_COMMIT_TAG" != "" ]]; then
        export DOCUMENTATION_VERSION=${CI_COMMIT_TAG%%.*}.x
        export ALIAS=latest
      else
        export DOCUMENTATION_VERSION=master
        export ALIAS=""
      fi
    - echo "DOCUMENTATION_VERSION $DOCUMENTATION_VERSION"
    - echo "ALIAS $ALIAS"
    - uv run mike deploy
      --update-aliases
      --alias-type=redirect
      --push
      --branch $PAGES_BRANCH
      --deploy-prefix public
      $DOCUMENTATION_VERSION $ALIAS
    - uv run mike set-default --push --branch $PAGES_BRANCH --deploy-prefix public latest || echo "The tag latest doesn't exist."
    - git checkout $PAGES_BRANCH
    - git log -1
  artifacts:
    expire_in: 30 days
    paths:
      - public/
