FROM registry.gitlab.ics.muni.cz:443/cryton/cryton/production-base:latest AS base

# Set environment
ENV POETRY_VIRTUALENVS_IN_PROJECT=true

WORKDIR /app

# Install dependencies
COPY poetry.lock pyproject.toml ./
RUN poetry install --without dev --no-root --no-interaction --no-ansi -E hive

# Install app
COPY . .
RUN poetry install --only-root --no-interaction --no-ansi -E hive

FROM python:3.12-slim-bullseye AS production

# Set environment
ENV CRYTON_APP_DIRECTORY=/app

# Copy app
COPY --from=base /app /app

# Make the executable accessible
RUN ln -s /app/.venv/bin/cryton-hive /usr/local/bin/cryton-hive

RUN _CRYTON_HIVE_COMPLETE=bash_source cryton-hive > /etc/profile.d/cryton-hive-complete.sh
RUN echo ". /etc/profile.d/cryton-hive-complete.sh" >> ~/.bashrc

CMD [ "cryton-hive", "start", "--migrate-database" ]
