FROM ghcr.io/astral-sh/uv:0.12.5-python3.12-alpine3.23 AS base

# Set environment
ENV UV_COMPILE_BYTECODE=1 \
    UV_LINK_MODE=copy \
    UV_PYTHON=3.12 \
    UV_PYTHON_DOWNLOADS=0 \
    UV_PROJECT_ENVIRONMENT=/app/.venv

WORKDIR /app

# Install dependencies
COPY uv.lock pyproject.toml ./
RUN uv sync --locked --no-dev --no-install-project --extra cli

# Install app
COPY . .
RUN uv sync --locked --no-dev --no-editable --extra cli

FROM python:3.12-alpine3.23 AS production

# Set environment
ENV CRYTON_APP_DIRECTORY=/app

# Install necessary packages
RUN apk add --no-cache \
    bash

# Copy app
COPY --from=base /app /app

# Make the executable accessible
RUN ln -s /app/.venv/bin/cryton-cli /usr/local/bin/cryton-cli

# Enable shell autocompletion
RUN _CRYTON_CLI_COMPLETE=bash_source cryton-cli > /etc/profile.d/cryton-cli-complete.sh
RUN echo ". /etc/profile.d/cryton-cli-complete.sh" >> ~/.bashrc

CMD [ "bash" ]
