FROM kalilinux/kali-last-release:latest AS kali

# Install packages
RUN apt update && apt install -y \
    python3 \
    medusa \
    nmap \
    wpscan \
    ffuf \
    && rm -rf /var/lib/apt/lists/*

FROM ghcr.io/astral-sh/uv:0.12.5 AS uv

FROM kali AS production

# Set environment
ENV CRYTON_APP_DIRECTORY=/app
ENV UV_COMPILE_BYTECODE=1 \
    UV_LINK_MODE=copy \
    UV_NO_CACHE=1 \
    UV_PYTHON=/usr/bin/python3 \
    UV_PYTHON_DOWNLOADS=0 \
    UV_PROJECT_ENVIRONMENT=/app/.venv

WORKDIR /app

# Copy uv
COPY --from=uv /uv /uvx /usr/local/bin/

# Install dependencies
COPY uv.lock pyproject.toml ./
RUN uv sync --locked --no-dev --no-install-project --extra worker

# Install app
COPY . .
RUN uv sync --locked --no-dev --no-editable --extra worker

# Make the executable accessible
RUN ln -s /app/.venv/bin/cryton-worker /usr/local/bin/cryton-worker

# Enable shell autocompletion
RUN _CRYTON_WORKER_COMPLETE=bash_source cryton-worker > /etc/profile.d/cryton-worker-complete.sh
RUN echo ". /etc/profile.d/cryton-worker-complete.sh" >> ~/.bashrc

CMD [ "cryton-worker", "start" ]
