x-settings: &settings
  # EMPIRE
  CRYTON_WORKER_EMPIRE_USERNAME: cryton
  CRYTON_WORKER_EMPIRE_PASSWORD: cryton
  # DATABASE
  POSTGRES_PASSWORD: cryton
  POSTGRES_USER: cryton
  POSTGRES_DB: cryton
  POSTGRES_HOST_AUTH_METHOD: md5
  # PGBOUNCER
  POSTGRESQL_HOST: cryton-db
  POSTGRESQL_USERNAME: cryton
  POSTGRESQL_DATABASE: cryton
  POSTGRESQL_PASSWORD: cryton
  PGBOUNCER_DATABASE: cryton
  PGBOUNCER_PORT: 5432
  PGBOUNCER_MAX_CLIENT_CONN: 1000
  PGBOUNCER_MIN_POOL_SIZE: 8
  PGBOUNCER_POOL_MODE: transaction
  # RABBIT
  RABBITMQ_DEFAULT_USER: cryton
  RABBITMQ_DEFAULT_PASS: cryton
  # METASPLOIT
  METASPLOIT_RPC_USERNAME: cryton
  METASPLOIT_RPC_PASSWORD: cryton
  METASPLOIT_DB_HOST: 127.0.0.1
  METASPLOIT_DB_PORT: 5432
  METASPLOIT_DB_NAME: cryton
  METASPLOIT_DB_USERNAME: cryton
  METASPLOIT_DB_PASSWORD: cryton
  METASPLOIT_DB_PREPARED_STATEMENTS: false
  METASPLOIT_DB_ADVISORY_LOCKS: false

services:
  cryton_db:
    restart: always
    image: postgres:16
    container_name: cryton-db
    environment:
      <<: *settings
    volumes:
      - cryton_db_data:/var/lib/postgresql/data
    healthcheck:
      test: /usr/bin/pg_isready -U $$POSTGRES_USER
      interval: 20s
      timeout: 10s
      retries: 5

  cryton_pgbouncer:
    restart: always
    image: bitnami/pgbouncer:1.22.1
    container_name: cryton-pgbouncer
    depends_on:
      cryton_db:
        condition: service_healthy
    environment:
      <<: *settings
    ports:
      - "127.0.0.1:5432:5432"  # This is open in case the user hosts Hive using pipx

  cryton_rabbit:
    restart: always
    image: rabbitmq:3.12-management
    container_name: cryton-rabbit
    environment:
      <<: *settings
    ports:
      - "5672:5672"
    healthcheck:
      test: rabbitmqctl eval '
        { true, rabbit_app_booted_and_running } = { rabbit:is_booted(node()), rabbit_app_booted_and_running },
        { [], no_alarms } = { rabbit:alarms(), no_alarms },
        [] /= rabbit_networking:active_listeners(),
        rabbitmq_node_is_healthy.
        ' || exit 1
      interval: 20s
      timeout: 10s
      retries: 5

  cryton_empire:
    restart: always
    image: bcsecurity/empire:v4.10.0
    container_name: cryton-empire
    environment:
      <<: *settings
    network_mode: host
    stdin_open: true
    entrypoint: []
    command: bash -c 'sudo -E poetry run python empire.py server --username $$CRYTON_WORKER_EMPIRE_USERNAME --password $$CRYTON_WORKER_EMPIRE_PASSWORD'

  cryton_msf:
    restart: always
    image: sadparad1se/metasploit-framework:rpc
    container_name: cryton-msf
    environment:
      <<: *settings
    network_mode: host
    tty: true
    depends_on:
      cryton_pgbouncer:
        condition: service_started

volumes:
  cryton_db_data:
