FROM ghcr.io/astral-sh/uv:0.12.5-python3.12-trixie-slim AS base

# Set environment
ENV UV_COMPILE_BYTECODE=1 \
    UV_LINK_MODE=copy \
    UV_PYTHON=3.12 \
    UV_PYTHON_DOWNLOADS=0 \
    UV_PROJECT_ENVIRONMENT=/app/.venv

WORKDIR /app

# Install dependencies
COPY uv.lock pyproject.toml ./
RUN uv sync --locked --no-dev --no-install-project --extra hive --extra modules

# Install app
COPY . .
RUN uv sync --locked --no-dev --no-editable --extra hive --extra modules

FROM python:3.12-slim-trixie AS production

# Set environment
ENV CRYTON_APP_DIRECTORY=/app

# Copy app
COPY --from=base /app /app

# Make the executable accessible
RUN ln -s /app/.venv/bin/cryton-hive /usr/local/bin/cryton-hive

RUN _CRYTON_HIVE_COMPLETE=bash_source cryton-hive > /etc/profile.d/cryton-hive-complete.sh
RUN echo ". /etc/profile.d/cryton-hive-complete.sh" >> ~/.bashrc

CMD [ "cryton-hive", "start", "--migrate-database" ]
