FROM httpd:2-alpine AS production

COPY docker/api-proxy/httpd.conf /usr/local/apache2/conf/httpd.conf
COPY docker/api-proxy/hp-vhosts.conf /usr/local/apache2/conf/extra/httpd-vhosts.conf
COPY docker/api-proxy/static /usr/local/apache2/web/static

RUN chmod -R 755 /usr/local/apache2/web/static
