[tox]
isolated_build = true
requires =
    tox>=4
    tox-uv-bare>=1.13
env_list = py{311,312,313,314},report

[testenv]
runner = uv-venv-lock-runner
uv_python_preference = managed
passenv = CRYTON_APP_DIRECTORY
setenv =
    file|settings
    py{311,312,313,314}: COVERAGE_FILE = .coverage.{envname}
extras = hive, modules, worker, cli
dependency_groups = dev
commands =
    pytest {posargs} --cov-append
depends =
    report: py{311,312,313,314}

[testenv:report]
runner = uv-venv-runner
deps = coverage
dependency_groups =
skip_install = true
allowlist_externals = bash
commands =
    coverage combine
    bash -c "coverage report > coverage.readable"
    coverage html
