release_version: 3
git_release: stable/3

python:
  min: 3.11
  max: 3.13

releases:
  cryton: https://gitlab.ics.muni.cz/cryton/cryton/-/releases/
  frontend: https://gitlab.ics.muni.cz/cryton/cryton-frontend/-/releases/

empire_version: 4.10.0
