from tests_e2e.tests.test_run_execution import TestRunExecution
from tests_e2e.tests.test_run_control import TestRunControl

from tests_e2e.tests.test_advanced import TestAdvancedExecution, TestAdvancedControl
from tests_e2e.tests.test_basic import TestBasicExecution, TestBasicControl
from tests_e2e.tests.test_empire import TestEmpireExecution
from tests_e2e.tests.test_http_trigger import TestHTTPTriggerExecution
from tests_e2e.tests.test_msf_trigger import TestMSFTriggerExecution
from tests_e2e.tests.test_datetime_trigger import TestDatetimeTriggerExecution
